### ISSUE TITLE
Feature Request: Hide the first heading

### ISSUE THREAD

**Issue by khanhtoan529** [xhuajin/obsidian-file-preview#13]
Use case: I use plugin "Sync heading with file name" to sync note title with the first heading of content. I use it because I want to have consitency look when open the file in other applications.

Problem: "File Preview" plugin display both file title + first heading (which is the same), it make a bit confusing
![image](https://github.com/user-attachments/assets/353bc1b7-6f0b-4c1c-a7cf-3359f501764f)

Expect result: Able to not display first heading in the content preview section

Thank you for your consideration

**Comment by greetclammy** [comment]
Was just about to make the same request! Yes please! This is a must. All my notes use the first line as title! Unfortunately, this makes "File Preview" not usable for me 😭

<img width="330" alt="Screen Shot 2024-10-20 at 17 33 21" src="https://github.com/user-attachments/assets/d4ab9e04-ba08-4fb1-9e02-121cd3a4b957">

**Comment by xhuajin** [comment]
Got it. I'll add that feature in next version.

**Comment by greetclammy** [comment]
Thank you!!! I forgot to mention that I also use [Auto Filename](https://github.com/rcsaquino/obsidian-auto-filename), a plugin that dynamically uses first line in note as note title (regardless if it's a header or not). If you could also add "Remove first line", I'd be eternally grateful! 🙌 This would allow one to replicate the Apple Notes experience in full!

To clarify, "Remove first line" could either include the first header (this would render the "Remove header" option redundant if "Remove first line" is enabled) **OR** first line after header (so the setting doesn't cause confusion for the end-user). I'll honestly take either!

**Comment by xhuajin** [comment]
This feature has been added in version 1.1.3!

**Comment by khanhtoan529** [comment]
@xhuajin I tested in sandbox vault. The options remove first heading is not work when a file has its properties:

![image](https://github.com/user-attachments/assets/195e5d1c-741b-4398-adba-b4cbecb65c66)
![image](https://github.com/user-attachments/assets/d518c955-9ba8-4ed4-a4a2-4bd0c00605d9)

Can you please take a look?
