### ISSUE TITLE
1.7.4新版obsidian启动时此插件失败

### ISSUE THREAD

**Issue by Qloulia** [xhuajin/obsidian-file-preview#14]
目前看下来好像电脑端和移动端都是如此，需要重新再设置中关闭再开启，才能正常在左栏文件管理器中显示

**Comment by xhuajin** [comment]
可能和其他插件冲突了，你在测试一下，因为我也是1.7.4，我这能正常打开，麻烦啦

**Comment by Qloulia** [comment]
确实确实，应该是和commander冲突了，我后来在试了几次都正常了！真是麻烦您了！

**Comment by xhuajin** [comment]
没事没事
