### ISSUE TITLE
Enable / disable Button

### ISSUE THREAD

**Issue by javiavid** [xhuajin/obsidian-file-preview#2]
Do you think you could add a button here to turn the content on and off?

<img width="388" alt="image" src="https://github.com/xhuajin/obsidian-file-preview/assets/7627504/2e3458df-fd12-42cc-9f28-7c0f43dce911">

**Comment by xhuajin** [comment]
Good advice, switching is easier. I add a button in v1.0.3

**Comment by javiavid** [comment]
You are very fast!, thank you very much
