### ISSUE TITLE
Support for obsidian mobile app

### ISSUE THREAD

**Issue by gaganyadav80** [xhuajin/obsidian-file-preview#5]
Thank you for this plugin. It does exactly what I was hoping obsidian had for a very long time. 
If possible please also support mobile devices.

<img src="https://github.com/xhuajin/obsidian-file-preview/assets/47142137/73231957-26aa-4218-9d06-f5c9cdb9b877" width="30%" >

**Comment by xhuajin** [comment]
Try it in 1.0.8

**Comment by gaganyadav80** [comment]
You are awesome! 🎉
