### ISSUE TITLE
请问您使用的是什么字体呢

### ISSUE THREAD

**Issue by taiyang95** [xhuajin/obsidian-file-preview#8]
![image](https://github.com/xhuajin/obsidian-file-preview/assets/172983808/ffe1433c-6484-4603-b258-51ff9eb933b2)
中文字体和英文字体是一起的么？
方便的话给个下载链接~谢谢啦

**Comment by taiyang95** [comment]
十分感谢~
另外提一点小建议，对于代码块，是否可以移除诸如\`\`\`java这样的md语法，这样可能预览的有用信息更直接一点。

**Comment by xhuajin** [comment]
> 十分感谢~ 另外提一点小建议，对于代码块，是否可以移除诸如```java这样的md语法，这样可能预览的有用信息更直接一点。

这个功能是有的，在设置里面可以开启删除代码块之类的格式化功能。

**Comment by taiyang95** [comment]
> > 十分感谢~ 另外提一点小建议，对于代码块，是否可以移除诸如```java这样的md语法，这样可能预览的有用信息更直接一点。
> 
> 这个功能是有的，在设置里面可以开启删除代码块之类的格式化功能。

我的意思是，如果markdown里是这样：
```java
public static void main(String args[]) {
    System.out.println("hello world");
}
```
我开启“删除代码块”，在文件列表中可以显示为：
xxx文件
public static void main(String args[]) {...
“删除代码块”是像删除加粗等，只是删除markdown语法，不删除内容。

当然，也可以保留“删除代码块”的旧有功能，新增一个设置~
