### ISSUE TITLE
[FR] 隐藏特定文本内容

### ISSUE THREAD

**Issue by Moyf** [xhuajin/obsidian-file-preview#9]
希望能从预览的文本中隐藏特定的内容：

1. H1 标题
2. Markdown 标记
3. 代码块
4. （可选）引用块

![image](https://github.com/user-attachments/assets/5bfa80c7-639c-4cf4-a974-9b008c9f0e85)

其一，很多人习惯在页面的开头加一个一级标题（和文件名相同），这样会导致冗余内容的显示：
![image](https://github.com/user-attachments/assets/717bb9d7-7940-4167-ab23-cca140694f05)

其二，希望能隐藏像是 `*` 或者 `-` 一类的 Markdown 字符，显示「纯文本」

其三，有时候页面开头会加上 ```dataview``` 之类的代码块，希望能隐藏掉这些代码块（针对3个或3个以上的反引号）；
其四也类似，希望能把 > 开头或者 ```ad-xxx``` 这样的 Callout 内容也隐藏起来，通常来说这些是「附加信息」而不是「有效正文」的内容。

![image](https://github.com/user-attachments/assets/742220d3-77a8-48ae-8697-866da0e50e1c)

___

最近在研究的另一个插件的更新（https://github.com/decaf-dev/obsidian-vault-explorer/releases/tag/1.27.0 ）也做了类似的功能配置，有需要的话可以参考：

> remove markdown from feed content: remove bold, italics, highlight characters, tables, 3 tick code blocks, markdown header hashes, wiki links

**Comment by xhuajin** [comment]
1.1.3 加了个正则匹配格式化文本，需要的话可以试试

**Comment by Moyf** [comment]
> 1.1.3 加了个正则匹配格式化文本，需要的话可以试试

太棒了！感谢~~
